use_frameworks!

target 'UICommonTools_Example' do
  pod 'UICommonTools', :path => '../'

  target 'UICommonTools_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
